export const AroundService = [
    {
        id: 101,
        name: 'Pak Budi Tukang Pipa',
        role: 'Tukang Pipa & Ledeng',
        rating: 4.9,
        review_count: 55,
        distance_km: 0.8, 
        category_id: '1',
        price_range: 'Rp 50.000 - 300.000',
        photo_url: '/assets/img/budi.jpg',
    },
    {
        id: 102,
        name: 'Ibu Rina Penjahit',
        role: 'Penjahit & Permak Kilat',
        rating: 4.8,
        review_count: 72,
        distance_km: 1.5,
        category_id: '3',
        price_range: 'Rp 25.000 - Rp 100.000',
        photo_url: '/assets/img/rina.jpg',
    },
    {
        id: 103,
        name: 'Fajar Servis AC',
        role: 'Teknisi AC & Kulkas',
        rating: 4.6,
        review_count: 31,
        distance_km: 2.1,
        category_id: '2',
        price_range: 'Rp 75.000 - 500.000',
        photo_url: '/assets/img/fajar.jpg',
    },
    {
        id: 104,
        name: 'Santi Cleaning Service',
        role: 'Jasa Bersih-Bersih Rumah',
        rating: 5.0,
        review_count: 12,
        distance_km: 0.5,
        category_id: '4',
        price_range: 'Rp 60.000 - Rp 350.000',
        photo_url: '/assets/img/santi.jpg',
    },
];